### ISSUE TITLE
Broke my computer

### ISSUE THREAD

**Issue by bdevorem** [cshinaver/KernelPi#3]
I managed to compile this somehow despite there being no documentation, and I burned the created image to my boot partition and now my laptop doesn't work. I blame you.

**Comment by jrjohnson1231** [comment]
Did you try turning it off and back on again?

**Comment by bdevorem** [comment]
Yes but it caught fire.

**Comment by jrjohnson1231** [comment]
That's because you burned it onto the boot partition, this seems like user error.

**Comment by bdevorem** [comment]
It was the only reasonable action, given the lack of documentation. Can I really be blamed?

**Comment by cshinaver** [comment]
Closed because user was bad. Bad user.

**Comment by bdevorem** [comment]
Wow.
